plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "pnpm run build"

# API routes - redirect to Netlify function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

# All other routes - serve the React app
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]